In [2]:
import pandas as pd 

metadata = pd.read_json(
    "../data/raw/meta-New_York.json.gz", 
    lines=True, 
    compression="gzip"
)

metadata.head()

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,A-Top Insurance,"A-Top Insurance, 1009 Brighton Beach Ave, Broo...",0x89c24469c758686b:0x641f5b84cb9bedfa,NaN,40.578254,-73.959127,"[Insurance broker, Insurance agency]",2.0,4,NaN,"[[Thursday, 10AM–6PM], [Friday, 10AM–6PM], [Sa...",None,Open ⋅ Closes 6PM,"[0x89c24449907718fb:0x31b554a0983f621d, 0x4065...",https://www.google.com/maps/place//data=!4m2!3...
1,T-Mobile,"T-Mobile, 3923 103rd St, Queens, NY 11368",0x89c25fc9494dce47:0x6d63c807b59a55,NaN,40.750146,-73.862536,"[Cell phone store, Electronic parts supplier, ...",3.5,95,$$,"[[Thursday, 10AM–8PM], [Friday, 10AM–8PM], [Sa...","{'Service options': ['In-store shopping', 'Del...",Open ⋅ Closes 8PM,"[0x89c25fc7a91c609f:0xb103d6a261373fd, 0x89c25...",https://www.google.com/maps/place//data=!4m2!3...
2,Ace Hardware,"Ace Hardware, 130 4th Ave, New York, NY 10003",0x89c259992463b6e1:0x4a601a43752541dd,"Chain retailer stocking household tools, suppl...",40.733182,-73.990201,"[Hardware store, Building materials store, Ele...",3.4,8,NaN,"[[Thursday, 8AM–6:30PM], [Friday, 8AM–6:30PM],...",None,Permanently closed,"[0x89c2598340fb6509:0xa996f3db49ba6e78, 0x89c2...",https://www.google.com/maps/place//data=!4m2!3...
3,"Agricultural Consulting Services, Inc.","Agricultural Consulting Services, Inc., 370 Su...",0x89d14bf74320aea5:0x720261cd8960f8cd,NaN,43.054743,-77.649136,[Corporate office],3.0,1,NaN,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",None,Open ⋅ Closes 5PM,None,https://www.google.com/maps/place//data=!4m2!3...
4,Long Point,"Long Point, Ledyard, NY 13026",0x89d0bd8d2df8d10f:0x77a8f349f40492fa,NaN,42.715626,-76.710227,[Peninsula],5.0,1,NaN,None,None,NaN,None,"https://www.google.com/maps/place/Ledyard,+NY+..."

In [3]:
metadata["category"].head(20)

0                  [Insurance broker, Insurance agency]
1     [Cell phone store, Electronic parts supplier, ...
2     [Hardware store, Building materials store, Ele...
3                                    [Corporate office]
4                                           [Peninsula]
5                                               [Diner]
6                                    [Auto parts store]
7     [Auto insurance agency, Home insurance agency,...
8               [Home inspector, Water testing service]
9                          [Spa, Waterproofing company]
10                                [High school, School]
11                                             [Doctor]
12                  [Tutoring service, Learning center]
13                                           [Attorney]
14                                                [Gym]
15                                  [Employment agency]
16                                  [Chocolate artisan]
17                                     [Parking garage]
18                                          [Sculpture]
19                                            [Charity]
Name: category, dtype: object

In [4]:
# find the most common categories
from collections import Counter 

category_counter = Counter()

for categories in metadata["category"].dropna():
    category_count.update(categories)

category_count.most_common(50)

NameError: name 'category_count' is not defined

In [ ]:
# inspect unique categories
all_categories = sorted(category_count.keys())

for category in all_categories: 
    print(category)

3D printing service
ATM
ATV dealer
ATV rental service
ATV repair shop
Abortion clinic
Abrasives supplier
Abundant Life church
Accountant
Accounting
Accounting firm
Accounting school
Accounting software company
Acoustical consultant
Acrylic store
Acupuncture clinic
Acupuncture school
Acupuncturist
Acura dealer
Addiction treatment center
Administrative attorney
Adoption agency
Adult DVD store
Adult day care center
Adult education school
Adult entertainment club
Adult entertainment store
Adult foster care service
Adventure sports
Adventure sports center
Advertising
Advertising agency
Advertising service
Aerial photographer
Aerial sports center
Aero dance class
Aerobics instructor
Aerospace company
Afghani restaurant
African goods store
African restaurant
After school program
Aged care
Aggregate supplier
Agricultural
Agricultural association
Agricultural cooperative
Agricultural organization
Agricultural product wholesaler
Agricultural production
Agricultural service
Agricultural service supply agency
Agriculture
Agriculture cooperative
Aikido school
Air compressor repair service
Air compressor supplier
Air conditioning contractor
Air conditioning repair service
Air conditioning store
Air conditioning system supplier
Air duct cleaning service
Air filter supplier
Air force base
Air taxi
Airbrushing service
Airbrushing supply store
Aircraft dealer
Aircraft maintenance company
Aircraft manufacturer
Aircraft rental service
Aircraft supply store
Airline
Airline ticket agency
Airplane
Airport
Airport parking lot
Airport shuttle service
Airport terminal
Airsoft supply store
Airstrip
Alcohol manufacturer
Alcoholic beverage wholesaler
Alcoholism treatment program
Alfa Romeo dealer
Allergist
Alliance church
Alsace restaurant
Alternative fuel station
Alternative medicine
Alternative medicine practitioner
Alternator supplier
Aluminum frames supplier
Aluminum supplier
Aluminum welder
Aluminum window
Amateur theater
Ambulance service
American football field
American grocery store
American restaurant
Amish furniture store
Ammunition supplier
Amphitheater
Amusement center
Amusement machine supplier
Amusement park
Amusement park ride
Amusement ride supplier
Anesthesiologist
Angler fish restaurant
Anglican church
Animal control service
Animal feed store
Animal hospital
Animal park
Animal protection organization
Animal rescue service
Animal shelter
Animal watering hole
Animals
Animation studio
Anime club
Anodizer
Antique furniture restoration service
Antique furniture store
Antique store
Apartment building
Apartment complex
Apartment rental agency
Apartments
Apostolic church
Appliance parts supplier
Appliance rental service
Appliance repair service
Appliance store
Appliances customer service
Appraiser
Apprenticeship center
Aquaculture farm
Aquarium
Aquarium shop
Aquatic centre
Arboretum
Arborist and tree surgeon
Archaeological museum
Archery event
Archery range
Archery store
Architect
Architects association
Architectural and engineering model maker
Architectural designer
Architectural salvage store
Architecture firm
Architecture school
Archive
Arena
Argentinian restaurant
Armenian church
Armenian restaurant
Army & navy surplus shop
Army facility
Army museum
Aromatherapy class
Aromatherapy service
Aromatherapy supply store
Art
Art cafe
Art center
Art dealer
Art gallery
Art handcraft
Art museum
Art restoration service
Art school
Art studio
Art supply store
Artificial plant supplier
Artist
Arts and crafts
Arts organization
Asbestos testing service
Ashram
Asian fusion restaurant
Asian grocery store
Asian household goods store
Asian restaurant
Asphalt contractor
Asphalt mixing plant
Assemblies of God church
Assembly room
Assisted living facility
Association or organization
Astrologer
Athletic club
Athletic field
Athletic park
Athletic track
Athletics
Atrium
Attorney
Attorney referral service
Attraction
Auction house
Audi dealer
Audio visual consultant
Audio visual equipment rental service
Audio visual equipment repair service
Audio visual equipment supplier
Audiologist
Auditor
Auditorium
Australian goods store
Australian restaurant
Austrian restaurant
Authentic Japanese restaurant
Auto accessories wholesaler
Auto air conditioning service
Auto auction
Auto body parts supplier
Auto body shop
Auto bodywork mechanic
Auto broker
Auto dent removal service
Auto electrical service
Auto glass shop
Auto insurance agency
Auto machine shop
Auto market
Auto painting
Auto parts manufacturer
Auto parts market
Auto parts store
Auto radiator repair service
Auto repair shop
Auto restoration service
Auto spring shop
Auto sunroof shop
Auto tag agency
Auto tune up service
Auto upholsterer
Auto window tinting service
Auto wrecker
Automation company
Automobile storage facility
Aviation
Aviation consultant
Aviation training institute
Awning supplier
Ayurvedic clinic
Açaí shop
BBQ area
BMW dealer
BMW motorcycle dealer
BMX park
BMX track
BPO company
BPO placement agency
Baby clothing store
Baby store
Baby swimming school
Badminton club
Badminton complex
Bag shop
Bagel shop
Bail bonds service
Bait shop
Bakery
Bakery equipment
Baking supply store
Ballet school
Ballet theater
Balloon artist
Balloon ride tour agency
Balloon store
Ballroom
Ballroom dance instructor
Band
Bangladeshi restaurant
Bank
Bank or ATM
Banking and finance
Bankruptcy attorney
Bankruptcy service
Banner store
Banquet hall
Baptist church
Bar
Bar & grill
Bar restaurant furniture store
Bar stool supplier
Bar tabac
Barbecue area
Barbecue restaurant
Barber school
Barber shop
Barber supply store
Barn
Bartending school
Baseball
Baseball club
Baseball field
Baseball goods store
Basilica
Basket supplier
Basketball
Basketball club
Basketball court
Basketball court contractor
Basque restaurant
Bathroom remodeler
Bathroom supply store
Battery manufacturer
Battery store
Battery wholesaler
Batting cage center
Battle site
Bay
Bazar
Beach
Beach cleaning service
Beach clothing store
Beach entertainment shop
Beach pavillion
Beach volleyball club
Beach volleyball court
Bead store
Bead wholesaler
Bearing supplier
Beautician
Beauty
Beauty product supplier
Beauty products wholesaler
Beauty salon
Beauty school
Beauty supply store
Bed & breakfast
Bed shop
Bedding store
Bedroom furniture store
Beer distributor
Beer garden
Beer hall
Beer store
Belgian restaurant
Belt shop
Bentley dealer
Beverage distributor
Beverages
Bicycle Shop
Bicycle club
Bicycle rack
Bicycle rental service
Bicycle repair shop
Bicycle store
Bicycle wholesale
Bicycles
Bike sharing station
Bike wash
Biking trail
Bikram yoga studio
Bilingual school
Billiards supply store
Bingo hall
Biofeedback therapist
Biotechnology company
Bird control service
Bird shop
Bird watching area
Birth center
Birth certificate service
Birth control center
Biryani restaurant
Bistro
Blacksmith
Blast cleaning service
Blinds shop
Blood bank
Blood donation center
Blood testing service
Blueprint service
Blues club
Board game club
Board of education
Boarding house
Boarding school
Boat accessories supplier
Boat builders
Boat club
Boat cover supplier
Boat dealer
Boat ramp
Boat rental service
Boat repair shop
Boat storage facility
Boat tour agency
Boat trailer dealer
Boating instructor
Bocce ball court
Body arts
Body piercing shop
Body shaping class
Boiler manufacturer
Boiler supplier
Bonsai plant supplier
Book publisher
Book store
Bookbinder
Bookkeeping service
Bookmaker
Books wholesaler
Boot camp
Boot repair shop
Boot store
Border crossing station
Botanical garden
Bottle & can redemption center
Bottled water supplier
Bouncy castle hire
Boutique
Bowling alley
Bowling club
Bowling supply shop
Box lunch supplier
Boxing club
Boxing gym
Boxing ring
Boys' high school
Brake shop
Brasserie
Brazilian pastelaria
Brazilian restaurant
Breakfast restaurant
Brewery
Brewing supply store
Brewpub
Brick manufacturer
Bricklayer
Bridal shop
Bridge
Bridge club
British restaurant
Brunch restaurant
Bubble tea store
Buddhist supplies store
Buddhist temple
Buffet restaurant
Buick dealer
Builder
Building
Building consultant
Building design company
Building equipment hire service
Building firm
Building inspector
Building materials market
Building materials store
Building materials supplier
Building restoration service
Burglar alarm store
Burmese restaurant
Burrito restaurant
Bus and coach company
Bus charter
Bus company
Bus depot
Bus station
Bus stop
Bus ticket agency
Bus tour agency
Buses
Business administration service
Business association local
Business banking service
Business broker
Business center
Business development service
Business management consultant
Business networking company
Business park
Business related
Business school
Business to business service
Butcher shop
Butcher shop deli
CD store
Cabaret club
Cabin rental agency
Cabinet maker
Cabinet store
Cable company
Cadillac dealer
Cafe
Cafeteria
Cajun restaurant
Cake decorating equipment shop
Cake shop
Californian restaurant
Call center
Call shop
Calvary Chapel church
Cambodian restaurant
Camera repair shop
Camera store
Camp
Camper shell supplier
Campground
Camping cabin
Camping farm
Camping store
Canadian restaurant
Canal
Cancer treatment center
Candle store
Candy store
Cannabis store
Cannery
Canoe & kayak rental service
Canoe & kayak store
Canoe & kayak tour agency
Canoe and kayak club
Canoeing area
Cantonese restaurant
Capoeira school
Car accessories store
Car alarm supplier
Car battery store
Car dealer
Car detailing service
Car factory
Car finance and loan company
Car inspection station
Car leasing service
Car manufacturer
Car racing track
Car rental
Car rental agency
Car repair and maintenance
Car security system installer
Car sharing location
Car stereo store
Car wash
Cardiologist
Care services
Career guidance service
Caribbean restaurant
Carnival club
Carpenter
Carpet cleaning service
Carpet installer
Carpet store
Carpet wholesaler
Carport and pergola builder
Carriage ride service
Cars
Carvery
Cash and carry wholesaler
Casino
Casket service
Castle
Cat boarding service
Caterer
Catering
Catering food and drink supplier
Cathedral
Catholic cathedral
Catholic church
Catholic school
Cattery
Cattle farm
Cattle market
Cave
Ceiling supplier
Cell phone accessory store
Cell phone charging station
Cell phone store
Cement supplier
Cemetery
Central American restaurant
Ceramic manufacturer
Ceramics wholesaler
Certification agency
Certified public accountant
Chalet
Chamber of Commerce
Channel
Chapel
Charcuterie
Charity
Charter school
Chartered accountant
Chauffeur service
Check cashing service
Cheese manufacturer
Cheese shop
Cheesesteak restaurant
Chemical exporter
Chemical industry
Chemical manufacturer
Chemical plant
Chemical wholesaler
Chess and card club
Chess club
Chess instructor
Chettinad restaurant
Chevrolet dealer
Chicken hatchery
Chicken restaurant
Chicken shop
Chicken wings restaurant
Child care agency
Child health care centre
Child psychiatrist
Child psychologist
Childbirth class
Children Policlinic
Children hall
Children's amusement center
Children's clothing store
Children's furniture store
Children's hospital
Children's museum
Children's party service
Childrens book store
Childrens cafe
Childrens club
Childrens farm
Childrens home
Childrens party buffet
Childrens store
Childrens theater
Chilean restaurant
Chimney services
Chimney sweep
Chinaware store
Chinese bakery
Chinese language instructor
Chinese language school
Chinese medicine clinic
Chinese medicine store
Chinese noodle restaurant
Chinese restaurant
Chinese supermarket
Chinese takeaway
Chinese tea house
Chiropractor
Chocolate
Chocolate artisan
Chocolate cafe
Chocolate factory
Chocolate shop
Choir
Chophouse restaurant
Christian book store
Christian church
Christian college
Christmas market
Christmas store
Christmas tree farm
Chrysler dealer
Church
Church of Christ
Church of Jesus Christ of Latter-day Saints
Church of the Nazarene
Church supply store
Churreria
Cider bar
Cider mill
Cigar shop
Circular distribution service
Circus
Citizen information bureau
City Department of Environment
City Department of Public Safety
City Hall
City administration
City clerk's office
City courthouse
City department of transportation
City district office
City government office
City park
City tax office
Civic center
Civil defense
Civil engineer
Civil engineering company
Civil examinations academy
Civil law attorney
Civil police
Class
Classified ads newspaper publisher
Cleaners
Cleaning products supplier
Cleaning service
Clergyman
Cliff
Clock repair service
Clock tower
Clock watch maker
Closed circuit television
Clothes and fabric manufacturer
Clothes and fabric wholesaler
Clothes market
Clothing
Clothing alteration service
Clothing store
Clothing supplier
Clothing wholesale market place
Clothing wholesaler
Club
Coaching center
Coal supplier
Coalfield
Coast guard station
Coat wholesaler
Cocktail bar
Coffee machine supplier
Coffee roasters
Coffee shop
Coffee stand
Coffee store
Coffee vending machine
Coffee wholesaler
Coffin supplier
Coin cashing machine
Coin dealer
Coin operated laundry equipment supplier
Cold cut store
Cold noodle restaurant
Cold storage facility
Collectibles store
College
Colombian restaurant
Comedy club
Comic book store
Commercial agent
Commercial cleaning service
Commercial photographer
Commercial printer
Commercial real estate agency
Commercial real estate inspector
Commercial refrigeration
Commercial refrigerator supplier
Commissioner for Oaths
Communications central
Community center
Community college
Community garden
Community health centre
Community school
Community service
Company
Company registry
Computer accessories store
Computer club
Computer consultant
Computer hardware manufacturer
Computer networking center
Computer repair service
Computer security service
Computer service
Computer software store
Computer store
Computer support and services
Computer training school
Computer wholesaler
Computers
Concert hall
Concrete contractor
Concrete factory
Concrete metal framework supplier
Concrete product supplier
Condiments supplier
Condominium complex
Condominium rental agency
Confectionery
Confectionery wholesaler
Conference center
Congregation
Conservation department
Conservative club
Conservative synagogue
Conservatory of music
Consignment shop
Construction
Construction and maintenance office
Construction company
Construction equipment supplier
Construction machine dealer
Construction machine rental service
Construction material wholesaler
Consultant
Contact lenses supplier
Container service
Container supplier
Container terminal
Containers supplier
Contemporary Louisiana restaurant
Continental restaurant
Contractor
Convenience store
Convenience stores organization
Convent
Convention center
Convention information bureau
Conveyor belt sushi restaurant
Cookie shop
Cooking class
Cooking school
Copier repair service
Copper supplier
Coppersmith
Copy shop
Copying supply store
Corporate campus
Corporate entertainment service
Corporate gift supplier
Corporate office
Correctional services department
Cosmetic dentist
Cosmetic products manufacturer
Cosmetic surgeon
Cosmetics
Cosmetics and perfumes supplier
Cosmetics industry
Cosmetics store
Cosmetics wholesaler
Cosplay cafe
Costa Rican restaurant
Costume jewelry shop
Costume rental service
Costume store
Cottage
Cottage rental
Cottage village
Cotton mill
Council
Counselor
Countertop contractor
Countertop store
Country club
Country food restaurant
Country house
Country park
County court
County government office
Courier & shipping services
Courier service
Court executive officer
Court reporter
Courthouse
Couscous restaurant
Couture store
Coworking space
Crab house
Craft store
Crane dealer
Crane rental agency
Crane service
Craniosacral therapy
Crater
Creche
Credit counseling service
Credit reporting agency
Credit union
Cremation service
Creole restaurant
Cricket club
Cricket ground
Cricket shop
Crime victim service
Criminal justice attorney
Crisis center
Croatian restaurant
Crop grower
Cruise agency
Cruise line company
Cruise terminal
Crushed stone supplier
Crêperie
Cuban restaurant
Culinary school
Cultural association
Cultural center
Cultural landmark
Culture
Cupcake shop
Cured ham store
Curling club
Currency exchange service
Curtain and upholstery cleaning service
Curtain store
Curtain supplier and maker
Custom home builder
Custom label printer
Custom t-shirt store
Custom tailor
Customs broker
Customs consultant
Customs office
Customs warehouse
Cutlery store
Cycling park
Czech restaurant
DJ service
DJ supply store
DS Automobiles dealer
DVD store
Dairy
Dairy farm
Dairy farm equipment supplier
Dairy store
Dairy supplier
Dam
Dan Dan noodle restaurant
Dance club
Dance company
Dance conservatory
Dance hall
Dance pavillion
Dance restaurant
Dance school
Dance store
Danish restaurant
Dart bar
Dart supply store
Data entry service
Data recovery service
Database management company
Dating service
Day care center
Day spa
Deaf church
Deaf service
Debris removal service
Debt collecting
Debt collection agency
Decal supplier
Deck builder
Deli
Delivery Chinese restaurant
Delivery Restaurant
Delivery service
Demolition contractor
Dental
Dental clinic
Dental hygienist
Dental implants periodontist
Dental implants provider
Dental insurance agency
Dental laboratory
Dental radiology
Dental school
Dental supply store
Dentist
Denture care center
Department of Public Safety
Department of Social Services
Department of Transportation
Department of education
Department of finance
Department of motor vehicles
Department store
Dermatologist
Design
Design agency
Design engineer
Design institute
Designer
Desktop publishing service
Dessert restaurant
Dessert shop
Detective
Detention center
Diabetes center
Diabetes equipment supplier
Diabetologist
Diagnostic center
Dialysis center
Diamond buyer
Diamond dealer
Diaper service
Diesel engine dealer
Diesel engine repair service
Diesel fuel supplier
Digital printer
Digital printing service
Dim sum restaurant
Diner
Dinner theater
Direct mail advertising
Dirt supplier
Disability equipment supplier
Disability services & support organisation
Disabled sports center
Disc golf course
Disciples of Christ Church
Disco club
Discount store
Discount supermarket
Display stand manufacturer
Disposable tableware supplier
Distance learning center
Distillery
Distributary
Distribution service
District Justice
District attorney
District council
District government office
District office
Dive club
Dive shop
Diving center
Divorce lawyer
Divorce service
Do-it-yourself shop
Dock builder
Doctor
Dodge dealer
Dog breeder
Dog cafe
Dog care
Dog day care center
Dog park
Dog trainer
Dog walker
Doll store
Dollar store
Domestic abuse treatment center
Domestic airport
Dominican restaurant
Donations center
Donut shop
Door manufacturer
Door shop
Door supplier
Door warehouse
Double glazing installer
Down home cooking restaurant
Drafting equipment supplier
Drafting service
Drainage service
Drama school
Drama theater
Drawing lessons
Dress and tuxedo rental service
Dress store
Dressmaker
Dried flower shop
Drilling contractor
Drinking water
Drinking water fountain
Drive-in movie theater
Driver and vehicle licensing agency
Driver's license office
Drivers license training school
Driveshaft shop
Driving school
Driving test centre
Drone shop
Drug store
Drug testing service
Drum school
Drum store
Dry cleaner
Dry fruit store
Dry ice supplier
Dry wall contractor
Dry wall supply store
Ducati dealer
Dude ranch
Dump truck dealer
Dumpling restaurant
Duty free store
Dynamometer supplier
E commerce agency
E-commerce service
Ear piercing service
Earth works company
East African restaurant
Eastern European restaurant
Eastern Orthodox Church
Eatery
Eating disorder treatment center
Eclectic restaurant
Ecological park
Economic consultant
Economic development agency
Ecuadorian restaurant
Education
Education and culture
Education center
Educational consultant
Educational institution
Educational supply store
Educational testing service
Eftpos equipment supplier
Egg supplier
Egyptian restaurant
Elder law attorney
Electric motor repair shop
Electric motor store
Electric utility company

In [6]:
# filtering relevant places

# create a dictionary with broad groups as keys and value as matching keywords 
activity_groups = {
    "Food & Drink": [
        "restaurant",
        "cafe",
        "coffee",
        "bakery",
        "bar",
        "ice cream",
        "deli",
        "bagel",
        "brewery"
    ],
    "Arts & Culture": [
        "museum",
        "art gallery",
        "theater",
        "theatre",
        "historical",
        "cultural center"
    ],
    "Outdoor & Nature": [
        "park",
        "garden",
        "beach",
        "hiking",
        "nature preserve",
        "trail"
    ],
    "Entertainment": [
        "tourist attraction",
        "movie theater",
        "bowling",
        "amusement park",
        "arcade",
        "escape room"
    ],
    "Sports & Recreation": [
        "gym",
        "sports complex",
        "swimming pool",
        "tennis",
        "golf",
        "skating rink"
    ],
    "Events & Nightlife": [
        "event venue",
        "night club",
        "music venue",
        "concert hall",
        "comedy club"
    ]
}

# takes in category of a business and return its broader group 
def get_activity_group(categories):
    if not isinstance(categories, list):
        return None

    # loops through every broad group in our dictionary 
    for group, keywords in activity_groups.items():
        
        # loop through the category list for that business 
        for category in categories:
            category_lower = category.lower()

            # match business' category to one of our broader groups 
            if any(keyword in category_lower for keyword in keywords):
                return group

    return None

# create new "broader group" column for data 
metadata["activity_group"] = metadata["category"].apply(get_activity_group)

# filter out rows that do not match our broader activities 
activity_metadata = metadata[
    metadata["activity_group"].notna()
]

activity_metadata.shape

(92741, 16)

Keyword filter for the categories for inital exploration, needs to be improved later on. 

Need to evaluate the filter and find false negatives/positives.

In [7]:
activity_metadata[
    ["name", "category", "activity_group", "avg_rating", "num_of_reviews"]
].head(20)

,name,category,activity_group,avg_rating,num_of_reviews
14,BK Pilates,[Gym],Sports & Recreation,4.8,8
17,NYC Parking Manhattan Avenue. Garage Corporation.,[Parking garage],Outdoor & Nature,3.7,8
23,Honeoye Creek Wildlife Management Area,"[Nature preserve, Park]",Outdoor & Nature,4.7,7
42,Dunkin',"[Coffee shop, Bagel shop, Bakery, Breakfast re...",Food & Drink,3.5,8
45,Staten Island Pool Rescue,[Swimming pool repair service],Sports & Recreation,5.0,2
46,"Express Pool Service, Corp",[Swimming pool contractor],Sports & Recreation,4.9,78
47,Driscoll RD Kayak Access point,[Nature preserve],Outdoor & Nature,4.8,5
52,Tivoli Bays Management Area Parking,[Park],Outdoor & Nature,4.5,2
54,Raffaello Kosher Pizza,[Restaurant],Food & Drink,3.4,8
64,Bloomers Floral & Gift,"[Florist, Flower delivery, Flower designer, Gi...",Food & Drink,4.9,45
68,Casa Malinche,[Mexican restaurant],Food & Drink,4.4,7
73,Dolce Gelateria,[Ice cream shop],Food & Drink,4.6,16
81,Kennedy's Chicken & Sandwiches,[Fast food restaurant],Food & Drink,3.7,8
85,Pantheon Properties - 399 Exterior,"[Parking lot, Real estate developer]",Outdoor & Nature,3.0,2
87,Claudio's Lounge,[Cocktail bar],Food & Drink,4.3,3
91,SoulCycle PKSP - Park Slope,"[Indoor cycling, Bicycle club, Gym, Physical f...",Sports & Recreation,4.7,19
93,Tony's Barber Shop,[Barber shop],Food & Drink,4.0,48
98,Cafe Kristall,"[Cafe, Restaurant]",Food & Drink,5.0,1
99,Liberty Theater,[Movie theater],Arts & Culture,4.5,8
100,dinkies,"[Bakery, Dessert shop, Restaurant]",Food & Drink,5.0,3

The broader activity groups can help us model user preferences with a simpler higher-level signal. 
It should also help with data sparsity and match users to places that they may not have been before, but fit into a category they have historically shown interest in. 

User1: 
Broader preferences: 
    50% food and drink
    25% entertainment 
    25% Outdoor & nature
Detailed:
    coffee shops: high
    mexican resturants: low 
    italian resturants: med
    parks: low 
    museums: med  

** We need to test how effective using both, or which combintation of both, makes the best recs.

In [15]:
# sample by each broad group, 25 samples per each
sample_by_group = (
    activity_metadata
    .groupby("activity_group", group_keys=False)
    .sample(n=25, random_state=42)
    .reset_index(drop = True)
)


sample_by_group[
    ["name", "category", "activity_group", "avg_rating", "num_of_reviews"]
]

,name,category,activity_group,avg_rating,num_of_reviews
0,NU MOVEMENT,"[Yoga studio, Art gallery, Ballroom dance inst...",Arts & Culture,5.0,6
1,Casagrain Gallery,[Art gallery],Arts & Culture,5.0,6
2,William Phelps General Store and Home Museum,"[Museum, Tourist attraction]",Arts & Culture,4.8,16
3,The Frame Shop,"[Picture frame shop, Art gallery]",Arts & Culture,5.0,17
4,Malta Drive-In Theatre,"[Drive-in movie theater, Movie theater]",Arts & Culture,4.5,768
...,...,...,...,...,...
145,Willow Brook Golf Club,"[Golf course, Golf club]",Sports & Recreation,4.3,53
146,Sagamore Golf Club,[Golf club],Sports & Recreation,4.5,47
147,Athletic Apex Health Clubs,"[Fitness center, Gym, Personal trainer, Swimmi...",Sports & Recreation,4.3,48
148,Nugent & Potter,"[Irrigation equipment supplier, Heating equipm...",Sports & Recreation,4.7,28
149,NY Kids Club - Brooklyn Heights,"[Preschool, After school program, Camp, Childr...",Sports & Recreation,2.7,3

In [16]:
# create a review copy of the sample groups 
sample_by_group = sample_by_group.copy()

sample_by_group["valid_activity"] = ""
sample_by_group["correct_group"] = ""
sample_by_group["notes"] = ""

review_sample = sample_by_group[
    [
        "name",
        "category",
        "activity_group",
        "avg_rating",
        "num_of_reviews", 
        "valid_activity",
        "correct_group",
        "notes"
    ]
]

# transfer to csv file for manual review 
review_sample.to_csv("activity_validation_sample.csv", index=False)

In [ ]:
# check through manual review 
validated_sample = pd.read_csv("activity_sample_validated.csv")
validated_sample["valid_activity"].value_counts()
validated_sample.groupby("activity_group")["valid_activity"].value_counts()

validated_sample[
    ["name", "category", "activity_group", "valid_activity", "correct_group", "notes"]
]

,name,category,activity_group,valid_activity,correct_group,notes
0,NU MOVEMENT,"['Yoga studio', 'Art gallery', 'Ballroom dance...",Arts & Culture,Yes,Yes,Additional categories may fit (sports and rec)
1,Casagrain Gallery,['Art gallery'],Arts & Culture,Yes,Yes,NaN
2,William Phelps General Store and Home Museum,"['Museum', 'Tourist attraction']",Arts & Culture,Yes,Yes,NaN
3,The Frame Shop,"['Picture frame shop', 'Art gallery']",Arts & Culture,Yes,Yes,NaN
4,Malta Drive-In Theatre,"['Drive-in movie theater', 'Movie theater']",Arts & Culture,Yes,Yes,NaN
...,...,...,...,...,...,...
145,Willow Brook Golf Club,"['Golf course', 'Golf club']",Sports & Recreation,Yes,Yes,NaN
146,Sagamore Golf Club,['Golf club'],Sports & Recreation,Yes,Yes,NaN
147,Athletic Apex Health Clubs,"['Fitness center', 'Gym', 'Personal trainer', ...",Sports & Recreation,Yes,Yes,NaN
148,Nugent & Potter,"['Irrigation equipment supplier', 'Heating equ...",Sports & Recreation,No,No,“swimming pool supply store” from “swimming”
149,NY Kids Club - Brooklyn Heights,"['Preschool', 'After school program', 'Camp', ...",Sports & Recreation,No,No,“Gymnastics” from “gym”

In [23]:
invalid_rows = validated_sample[
    validated_sample["valid_activity"].str.lower() == "no"
]

invalid_rows[
    ["name", "category", "activity_group", "valid_activity", "correct_group", "notes"]
]

,name,category,activity_group,valid_activity,correct_group,notes
50,Majestic Woods NY,"['Event venue', 'Wedding venue']",Events & Nightlife,No,Yes,"“Event venue”, “wedding venue”"
51,"Country Inn & Suites by Radisson, Lake George ...","['Hotel', 'Business center', 'Event venue', 'G...",Events & Nightlife,No,Yes,“Event venue”
53,The Yard: Herald Square Coworking Office Space...,"['Office space rental agency', 'Business to bu...",Events & Nightlife,No,Yes,“Event venue”
54,DOLAJ EVENT SPACE,['Event venue'],Events & Nightlife,No,Yes,“Event venue”
57,Convene,"['Event venue', 'Business center', 'Conference...",Events & Nightlife,No,Yes,“Event venue”
58,Bean Acres Barn Weddings,"['Wedding venue', 'Event venue', 'Wedding chap...",Events & Nightlife,No,Yes,"“Event venue”, “wedding venue”"
59,"718 Studios - Film & Photo Studio Brooklyn, NYC","['Photography studio', 'Event venue', 'Film pr...",Events & Nightlife,No,Yes,“Event venue”
60,Palki Party Center,['Event venue'],Events & Nightlife,No,Yes,“Event venue”
61,One EPIC Place,"['Coworking space', 'Business center', 'Coachi...",Events & Nightlife,No,Yes,“Event venue”
62,Grace Hall Club,['Event venue'],Events & Nightlife,No,Yes,“Event venue”
64,Ivory Acres Wedding Venue,"['Wedding venue', 'Event venue']",Events & Nightlife,No,Yes,"“Event venue”, “wedding venue”"
65,Willow Drey Farm,['Event venue'],Events & Nightlife,No,Yes,“Event venue”
66,620 Loft & Garden,['Event venue'],Events & Nightlife,No,Yes,“Event venue”
67,Blue Arrow Farm,"['Horse boarding stable', 'Animal rescue servi...",Events & Nightlife,No,Yes,“Event venue”
68,Town & Country Caterers,"['Wedding venue', 'Caterer', 'Event venue']",Events & Nightlife,No,Yes,NaN
70,Ariana's South,"['Event venue', 'Banquet hall', 'Caterer', 'We...",Events & Nightlife,No,Yes,NaN
73,Niagara Shores Campground and Conference Center,"['Indoor lodging', 'Campground', 'Conference c...",Events & Nightlife,No,Yes,NaN
74,Sleep Inn & Suites Buffalo Airport,"['Hotel', 'Event venue']",Events & Nightlife,No,Yes,NaN
107,STS Trailer & Truck Equipment - Albany,['Trailer dealer'],Outdoor & Nature,No,No,“Trailer dealer” from “trail”
117,Gedney Farms Nursery,"['Plant nursery', 'Garden center']",Outdoor & Nature,No,No,"“Plant nursery”, “garden center”"
119,Reliable Garden & Ponds,"['Garden center', 'Animal control service', 'F...",Outdoor & Nature,No,No,“Garden center”
128,Vega Gymnastics,['Gymnastics center'],Sports & Recreation,No,No,“Gymnastics” from “gym”
129,International Boxing & Fitness,"['Boxing gym', 'After school program', 'Gym', ...",Sports & Recreation,No,Yes,Not an activity
130,B & D Pool & Spa,['Swimming pool contractor'],Sports & Recreation,No,No,“Swimming pool contractor” from “swimming”
134,Pool Therapist Management,['Swimming pool repair service'],Sports & Recreation,No,No,“Swimming pool repair” from “swimming”
148,Nugent & Potter,"['Irrigation equipment supplier', 'Heating equ...",Sports & Recreation,No,No,“swimming pool supply store” from “swimming”
149,NY Kids Club - Brooklyn Heights,"['Preschool', 'After school program', 'Camp', ...",Sports & Recreation,No,No,“Gymnastics” from “gym”

After manually looking through the broader groups, we have new exclusion rules:
"repair", "contractor", "supply", "parking", "service"

Arts and culture and food and drink were very consistant, while events and nightlife and sports and recriation had many invalid activities, or ambiguous ones.

Improvements for next taxonomy